version: "3.8"
services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/localhost.pem
      - REGISTRY_HTTP_TLS_KEY=/certs/localhost-key.pem
    volumes:
      - ./certs:/certs
